spring.application.name=duri-auth

spring.profiles.active=${ACTIVE_PROFILE}

# Disable DB for RUN Application
## DB NOT connected yet
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration