spring.application.name=duri-auth

spring.profiles.active=${ACTIVE_PROFILE}

# JWT
jwt.issuer=duri-auth
jwt.access.validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.refresh.validity=${JWT_REFRESH_TOKEN_VALIDITY}