# Server Port for PROD
server.port=${SERVER_PORT_PROD}

# DB
spring.datasource.url=jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DB}
spring.datasource.username=${MARIA_USERNAME}
spring.datasource.password=${MARIA_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JWT
jwt.issuer=duri-auth
jwt.access.validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
# MVP : Refresh Token 사용X
# jwt.refresh.validity=${JWT_REFRESH_TOKEN_VALIDITY}

# Cookie
web.cookie.domain=.duri.asia
web.cookie.access-path=/
web.cookie.is-secure=true
web.cookie.same-site=None
web.cookie.access-max-age=86400

# MVP : Refresh Token 사용X
# web.cookie.refresh-path=/auth
# web.cookie.refresh-max-age=21600

# CORS
#cors.allowed-origins=https://www.duri.asia

# Eureka
# TODO: URL 수정 필요
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eureka.duri.asia/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.file.name=/logs/app.log
logging.logback.rollingpolicy.max-file-size=50MB
logging.logback.rollingpolicy.max-history=14
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger - %msg%n