# Server Port for DEV
server.port=${SERVER_PORT_DEV}

# JPA Setting
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Local DEV DB Connection
spring.datasource.url=${MARIADB_LOCAL_URL}
spring.datasource.username=${MARIADB_LOCAL_USERNAME}
spring.datasource.password=${MARIADB_LOCAL_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Local Redis Connection
spring.data.redis.host=${REDIS_LOCAL_HOST}
spring.data.redis.port=${REDIS_LOCAL_PORT}

# Local Redis Setting
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.lettuce.pool.max-wait=1s

# Cookie (DEV)
web.cookie.domain=
web.cookie.access-path=/
web.cookie.refresh-path=/auth
web.cookie.access-max-age=1800
web.cookie.refresh-max-age=21600