# Server Port for PROD
server.port=${SERVER_PORT_PROD}

# JWT
jwt.issuer=duri-auth
jwt.access.validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
# MVP : Refresh Token 사용X
# jwt.refresh.validity=${JWT_REFRESH_TOKEN_VALIDITY}

# Cookie
web.cookie.domain=localhost
web.cookie.access-path=/
# MVP : Access Token ONLY (24h)
web.cookie.access-max-age=86400

# MVP : Refresh Token 사용X
# web.cookie.refresh-path=/auth
# web.cookie.refresh-max-age=21600